packages:
  - "apps/*"
  - "packages/*"

catalog:
  zod: "^4.1.13"
  "@orpc/server": "^1.12.3"
  "@orpc/client": "^1.12.3"
  "@orpc/contract": "^1.12.3"
  "@orpc/openapi": "^1.12.3"
  "@orpc/zod": "^1.12.3"
  "@orpc/tanstack-query": "^1.12.3"
  "better-auth": "^1.4.6"
  "@better-auth/expo": "^1.4.6"
  dotenv: "^17.2.2"
  drizzle-orm: "^0.45.1"
  effect: "^3.19.11"
  next: "^16.0.10"
  "@tanstack/react-query": "^5.90.12"
  "@tanstack/react-query-devtools": "^5.90.12"
  "@t3-oss/env-nextjs": "^0.13.8"
  "@types/react": "^19.2.7"
  "@types/react-dom": "^19.2.3"
  "@types/node": "^24.10.1"
  typescript: "^5.9.3"
  uuidv7: "^1.1.0"
