packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/expo': ^1.4.9
  '@orpc/client': ^1.13.0
  '@orpc/contract': ^1.13.0
  '@orpc/openapi': ^1.13.0
  '@orpc/server': ^1.13.0
  '@orpc/tanstack-query': ^1.13.0
  '@orpc/zod': ^1.13.0
  '@t3-oss/env-nextjs': ^0.13.10
  '@tanstack/react-query': ^5.90.12
  '@tanstack/react-query-devtools': ^5.91.1
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  better-auth: ^1.4.9
  dotenv: ^17.2.2
  drizzle-orm: ^0.45.1
  effect: ^3.19.13
  next: ^16.1.1
  temporal-polyfill: ^0.3.0
  typescript: ^5.9.3
  uuidv7: ^1.1.0
  zod: ^4.2.1
