import { Platform } from "react-native";
import { THEME } from "@/lib/theme";

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  },
});

export const lightColors = {
  background: THEME.light.background,
  foreground: THEME.light.foreground,
  card: THEME.light.card,
  cardForeground: THEME.light.cardForeground,
  popover: THEME.light.popover,
  popoverForeground: THEME.light.popoverForeground,
  primary: THEME.light.primary,
  primaryForeground: THEME.light.primaryForeground,
  secondary: THEME.light.secondary,
  secondaryForeground: THEME.light.secondaryForeground,
  muted: THEME.light.muted,
  mutedForeground: THEME.light.mutedForeground,
  accent: THEME.light.accent,
  accentForeground: THEME.light.accentForeground,
  destructive: THEME.light.destructive,
  destructiveForeground: THEME.light.destructiveForeground,
  border: THEME.light.border,
  input: THEME.light.input,
  ring: THEME.light.ring,
  text: THEME.light.foreground,
  textMuted: THEME.light.mutedForeground,
  icon: THEME.light.mutedForeground,
  blue: "#007AFF",
  green: "#34C759",
  red: "#FF3B30",
  orange: "#FF9500",
  yellow: "#FFCC00",
  pink: "#FF2D92",
  purple: "#AF52DE",
  teal: "#5AC8FA",
  indigo: "#5856D6",
};

export const darkColors = {
  background: THEME.dark.background,
  foreground: THEME.dark.foreground,
  card: THEME.dark.card,
  cardForeground: THEME.dark.cardForeground,
  popover: THEME.dark.popover,
  popoverForeground: THEME.dark.popoverForeground,
  primary: THEME.dark.primary,
  primaryForeground: THEME.dark.primaryForeground,
  secondary: THEME.dark.secondary,
  secondaryForeground: THEME.dark.secondaryForeground,
  muted: THEME.dark.muted,
  mutedForeground: THEME.dark.mutedForeground,
  accent: THEME.dark.accent,
  accentForeground: THEME.dark.accentForeground,
  destructive: THEME.dark.destructive,
  destructiveForeground: THEME.dark.destructiveForeground,
  border: THEME.dark.border,
  input: THEME.dark.input,
  ring: THEME.dark.ring,
  text: THEME.dark.foreground,
  textMuted: THEME.dark.mutedForeground,
  icon: THEME.dark.mutedForeground,
  blue: "#0A84FF",
  green: "#30D158",
  red: "#FF453A",
  orange: "#FF9F0A",
  yellow: "#FFD60A",
  pink: "#FF375F",
  purple: "#BF5AF2",
  teal: "#64D2FF",
  indigo: "#5E5CE6",
};

export const Colors = {
  light: lightColors,
  dark: darkColors,
};
